resources:
  - config.yaml
  - infra.yaml
  - apps.yaml
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/enableServiceLinks
        value: false
